spring:
  application:
    name: board_practice
  profiles:
    include: oauth

  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:~/test;mode=oracle


  h2:
    console:
      path: /h2-console
      enabled: true

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl